### DISCUSSION TITLE
Looking for review for Shadowdark SRD proposal

### DISCUSSION THREAD

**Discussion by RagingRoosevelt** [Obsidian-TTRPG-Community/TTRPG-Community-Admin#32] [Ask an Inquisitor]
Hi!  My friend is getting into Shadowdark and I wanted to support them with adding support in Fantasy Statblocks for it.  I've put together what I think is a reasonable layout and have started creating monster statblocks, copied from the official rulebook.  I'd like for this to eventually be able to become one of this project's SRDs and so to that end, I hope that I could get pointers if I'm heading in a good direction before I commit and get the rest of the monsters produced.

I've attached a copy of the layout I've built ([Shadowdark.json](https://github.com/user-attachments/files/17551096/Shadowdark.json)), and here are a couple of sample monster YAMLs, with the corresponding statblocks, compared to how they look in the official rulebook:

berserker.md:

```yaml
columns: 2
forcecolumns: true
layout: Shadowdark
source: CRB
sourcebook: _Core Rulebook_, page 199
name: "Berserker"
description: Howling, battleraging warriors.
level: 2
alignment: Neutral
abilityMods: [2, 1, 1, 0, 1, 0]
speed: near

ac: 12
armorclass:
  - name: AC
    desc: "12 (leather)"

hp: 10
health:
  - name: HP
    desc: "10"

attack_actions: 1 Greataxe or 1 Spear
attacks:
  - name: Greataxe
    desc: +2 __Damage__ (1d10)
  - name: Spear
    desc: +2 (close/near) __Damage__ (1d6)

abilities:
  - name: Rage
    desc: 1/day, immune to morale checks, +1d4 damage (3 rounds).
```
![Berserker](https://github.com/user-attachments/assets/010355d6-ef8f-4f32-ad08-8a7124ec8ac1)
![Bandit in Rule Book](https://github.com/user-attachments/assets/877eedda-5274-427f-bb54-2f4d32cac092)

```yaml
columns: 2
forcecolumns: true
layout: Shadowdark
source: CRB
sourcebook: _Core Rulebook_, page 197
name: "Bandit"
description: Hard-bitten rogue in tattered leathers and a hooded cloak.
level: 1
alignment: Chaotic
abilityMods: [2, 0, 0, -1, 0, -1]
speed: near

ac: 13
armorclass:
  - name: AC
    desc: "13 (leather & shield)"

hp: 4
health:
  - name: HP
    desc: "4"

attack_actions: 1 Club or 1 Shortbow
attacks:
  - name: Club
    desc: +1 __Damage__ (1d4)
  - name: Shortbow
    desc: +0 (far) __Damage__ (1d4)

abilities:
  - name: Ambush
    desc: Deal an extra die of damage when undetected.
```
![Bandit](https://github.com/user-attachments/assets/774a7c4a-592d-44cd-867c-863ee55e32df)
![Bandit in Rule Book](https://github.com/user-attachments/assets/8deaf57c-fce4-4668-b3fe-8213517c95ee)

The items I have on my roadmap are
- [ ] add tokens
- [ ] get dice parsing working
- [ ] decide how I want to add traits, especially since the rulebook doesn't have any traits (humanoid, animal, undead, etc) mentioned in it

How does this look?  Would you adjust how I'm tackling these?

As far as making sure the license of Shadowdark is compatible with this sort of compendium, in the rules, there is this in the license (Core Rulebook, page 325): 

> You may not print verbatim passages of text (no matter the length) from the game, with the exception of monsters, spells, and magic items.

From what I can tell, it seems like that's intended to support VTTs and tools like what we're working on in Obsidian.
